num_threads: 16
data:
  data_path: '/home/dl/Documents/phd/data/boreas'
  meas_path: '/home/dl/Documents/phd/dev/dr_ba/output'
output:
  output_path: '/home/dl/Documents/phd/dev/dr_ba/output/ba_results'
  visualize: true
  save_result: false
localization:
  seq_id: boreas-2024-12-23-16-27
  map_seq_id: boreas-2024-12-05-14-12
  map_location: '/home/dl/Documents/phd/dev/dr_ba/output/aaa_paper_results/gt_maps/boreas-2024-12-05-14-12/'
  start_frame: 0
  end_frame: -1
  odometry_prior:
    use_odometry_prior: false
    translation_std: 0.1  # m
    rotation_std: 0.1  # degrees
  frame_processing:
    input_type: 'local_maps' # 'scans' or 'local_maps' with both being images (for now)
    local_map_res: 0.1  # m/pixel (only relevant if input_type is 'local_map')
    max_dist: 100.0  # m
    adaptive_blur: false # adaptively choose Gaussian blur sigma based on scan content
    gauss_blur_sigma: 3.0  # pixels
    min_int_val_tol: 0.5 # min intensity value to consider a non-zero pixel
    min_percent_nonzero: 0.3 # Minimum percent of scan pixels above min_int_val_tol to stop blurring scan
  optimization:
    max_iterations: 15
    convergence_tol: 1e-3
    alpha: 1.0  # step size
    meas_std: 0.1 # intensity units
    range_factor: 0.0005  # factor to scale range uncertainty to intensity uncertainty
    use_cumul_thresh: true
    zero_thresh: 0.2 # max cumul return threshold to consider a measurement as zero return
    cumul_thresh: 0.9  # threshold to ignore measurements with too high a cumulative return
    rel_pose_prior:
      use_pose_prior: false
      translation_std: 1.0  # m
      rotation_std: 0.1  # degrees
    max_loaded_scans: 400  # max number of scans to keep loaded in memory at once (<1 all)