map:
  voxel_res: 1.0
output:
  output_path: /home/dl/Documents/phd/dev/dr_ba/output/map_loc_ablation/set_06
  visualize: true
  save_result: true
input:
  data_path: /home/dl/Documents/phd/data/boreas
  meas_path: /home/dl/Documents/phd/dev/dr_ba/output
  seq_id: boreas-2024-12-04-11-56
  max_dist: 100.0
  dist_field_preproc: false
  gauss_blur_sigma: 3.0
  init_poses: gt
  init_translation_std: 0.0
  init_rotation_std: 0.0
  input_type: local_maps
  local_map_res: 0.1
  map_id: boreas-2024-12-04-11-45
keyframing:
  max_kf_dist: 5.0
  max_kf_rot: 30.0
  fix_first_scan: true
optimization:
  num_threads: 16
  max_iterations: 20
  convergence_tol: 1e-3
  alpha: 1.0
  adaptive_alpha: true
  meas_std: 0.1
  range_factor: 0.0005
  use_cumul_thresh: true
  zero_thresh: 0.1
  cumul_thresh: 0.9
  rel_pose_prior:
    use_pose_prior: false
    translation_std: 100.0
    rotation_std: 0.1
  num_coarse_iterations: 0
  coarse_downsample: 0.2
  refine_downsample: 1.0
  tile_size: 100.0
  max_loaded_scans: 300
mapping:
  map_seq: boreas-2024-12-04-11-45
  pose_source: gt
  estimate_location: /home/dl/Documents/phd/dev/dr_ba/output/ba_results/run_52
  max_dist: 80.0
  dist_field_preproc: false
  gauss_blur_sigma: 3.0
  frame_ranges:
  - - 0
    - -1
localization:
  map_location: /home/dl/Documents/phd/dev/dr_ba/output/ba_results/map_29
  start_frame: 0
  end_frame: -1
