num_threads: 16
seed: 99 # random seed for reproducibility, <0 for random
data:
  data_path: /path/to/boreas/data
  meas_path: /path/to/this/repo/output
output:
  output_path: /path/to/this/repo/output/map_results
  visualize: true
  save_result: true
mapping:
  voxel_res: 10.0  # m
  seq_id: boreas-2024-12-05-14-12
  estimate_location: /path/to/ba/estimate/location
  frame_ranges:
  - [0, -1]
  pose_source: 'estimate' # 'estimate, 'gt', 'pogo', 'dro'
  init_translation_std: 0.0  # m
  init_rotation_std: 0.0  # degrees
  keyframing:
    max_kf_dist: 5.0  # m
    max_kf_rot: 30.0  # degrees
    fix_first_scan: true
  frame_processing:
    input_type: 'local_maps' # 'scans' or 'local_maps' with both being images (for now)
    local_map_res: 0.1  # m/pixel (only relevant if input_type is 'local_map')
    max_dist: 100.0  # m
    adaptive_blur: false # adaptively choose Gaussian blur sigma based on scan content
    gauss_blur_sigma: 3.0  # pixels
    min_int_val_tol: 0.5 # min intensity value to consider a non-zero pixel
    min_percent_nonzero: 0.3 # Minimum percent of scan pixels above min_int_val_tol to stop blurring scan
  optimization:
    meas_std: 0.1 # intensity units
    range_factor: 0.0005  # factor to scale range uncertainty to intensity uncertainty
    use_cumul_thresh: true
    zero_thresh: 0.2 # max cumul return threshold to consider a measurement as zero return
    cumul_thresh: 0.9  # threshold to ignore measurements with too high a cumulative return
    tile_size: 100.0  # m, size of tiles to process separately
    max_loaded_scans: 300  # max number of scans to keep loaded in memory at once (<1 all)